# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: receipt_verifier.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'receipt_verifier.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16receipt_verifier.proto\x12\x10receipt_verifier\"\x1a\n\nBytesChunk\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\"b\n\x12GrpcVerifyResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x1a\n\rjournal_value\x18\x03 \x01(\rH\x00\x88\x01\x01\x42\x10\n\x0e_journal_value2u\n\x16ReceiptVerifierService\x12[\n\x13VerifyReceiptStream\x12\x1c.receipt_verifier.BytesChunk\x1a$.receipt_verifier.GrpcVerifyResponse(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'receipt_verifier_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BYTESCHUNK']._serialized_start=44
  _globals['_BYTESCHUNK']._serialized_end=70
  _globals['_GRPCVERIFYRESPONSE']._serialized_start=72
  _globals['_GRPCVERIFYRESPONSE']._serialized_end=170
  _globals['_RECEIPTVERIFIERSERVICE']._serialized_start=172
  _globals['_RECEIPTVERIFIERSERVICE']._serialized_end=289
# @@protoc_insertion_point(module_scope)
